### ISSUE TITLE
Having  error : /usr/bin/bish-bosh: 6399: read: arg count

### ISSUE THREAD

**Issue by Skorkmaz88** [raphaelcohn/bish-bosh#9]
I used debian release package and I am having issue with sending data from file : 

**/usr/bin/bish-bosh: 6399: read: arg count
bish-bosh: FAIL: processLoop failed**

When trying to publish from file

System: ubuntu 16.04, x64 .

**Comment by raphaelcohn** [comment]
I'm not currently able to offer ad-hoc support for bish-bosh because of time constraints (ie I don't have any), but a few pointers to some things to look into:-

* Have you tried using the source as-is from GitHub?
* Do you know which shell you're running this in?
* Can you add `set -x` to the shell script code, and try to see what's going on around the error?

**Comment by Skorkmaz88** [comment]
I totally understand the time issue

 - No, I used the latest release, so I think it is not up to date with source ? 

 - Shell version: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

 - I am no longer using this, but something else at the moment, I will try to get old settings and run in this mode and add the results.

**Comment by raphaelcohn** [comment]
Ta
